"""empty message

Revision ID: c8903c364236
Revises: 
Create Date: 2018-06-13 15:12:49.377618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8903c364236'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_details',
    sa.Column('employeeId', sa.Integer(), nullable=False),
    sa.Column('employeeName', sa.String(length=10), nullable=False),
    sa.Column('phoneNo', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=20), nullable=False),
    sa.Column('createdAt', sa.Integer(), nullable=False),
    sa.Column('updatedAt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('employeeId')
    )
    op.create_table('employee_sports',
    sa.Column('sportId', sa.Integer(), nullable=False),
    sa.Column('sportName', sa.String(length=20), nullable=False),
    sa.Column('employeeId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.Integer(), nullable=False),
    sa.Column('updatedAt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employeeId'], ['employee_details.employeeId'], ),
    sa.PrimaryKeyConstraint('sportId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_sports')
    op.drop_table('employee_details')
    # ### end Alembic commands ###
